### ISSUE TITLE
Always generate an explicit select list instead of select *

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/virtual-schema-common-java#188]
## Problem

There is an optimization on the database side that turns a Virtual Schema SELECT statement containing an explicit list of columns into a SELECT * query when the select list contains all the columns from metadata. 

## Solution

We can use an `involvedTables` field of the pushdown request to create an explicit select list with column names.

## See also

* Fixes exasol/elasticsearch-virtual-schema#4.

**Comment by mwellbro** [comment]
Hi guys, sorry, I´m a bit new to this so I might be miss-reading the label, but the mentioned optimization leads to an error / abort when accessing tables containing columns which are not supported by the virtual schema ( example: HANA, tables including VARBINARY ) - the correction of this behavior is a "feature" ?

**Comment by redcatbear** [comment]
The core database contracts complete select lists to "*". That is the bug-part if you will, since this is where user intent is lost at this point. It was intended as an optimization, but turned out to have unwanted side effects (e.g. causing problems with hidden or unsupported columns).

That the VS expands the "*" into a list of columns, is a new feature of the Virtual Schema.
We will be adding the feature to the VS to counteract the contraction. This helps with the problem on older database versions. Depending on how well that works, the core will then decide whether or not to address the contraction issue.
