### ISSUE TITLE
Preparations for separate adapter in virtual-schema-common

### ISSUE THREAD

**Issue by redcatbear** [exasol/virtual-schema-common-java#2]
# Situation
We cut the common parts of the Virtual Schemas to `virtual-schema-common` in preparation of supporting multiple separate adapters (e.g. the [GitHub adapter](https://github.com/exasol/virtual-schema-github-adapter)).

Some clean-up is required in order for this repository to be fully independent of the previous place.

**Comment by andrehacker** [comment]
Morning, the current name of the repo does not include java, i.e. when we add a python common module, what should we do?
I think the (new) naming of the maven module is fine though, since "java" is implicitly there. Any thoughts?

**Comment by redcatbear** [comment]
@andrehacker you make a convincing argument and I like explicit naming anyway.
I am going to change the module name and repository name to `virtual-schema-common-java`.

**Comment by andrehacker** [comment]
Well, I personally think the module name was fine, since calling a module with suffix -java feels a bit strange to me as most modules I know don't have this suffix (and for me it is not important that the github repo name is the same). But just my personal opinion, I can also live with a renamed version.
